### ISSUE TITLE
Make DB path absolute, not relative

### ISSUE THREAD

**Issue by hintron** [Victory-Game-Studios/Oldentide#23]
Currently, the server sqlite db file is `db/Oldentide.db`. It's a relative path. I think it might be better if we create an absolute location for this to go. As it currently stands, you have to run the Server executable in ...`/Oldentide/Server/` for it to find the database. The executable shouldn't need to depend on where you run it. 

I suggest we put it in a fixed location. I'm not sure where, but it could be someplace like `/var/lib/Oldentide/` (`/var/lib/` seems to be where dbs go - see [https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)).

**Comment by Jldevictoria** [comment]
I think an argument can be made for allowing the db to be placed anywhere the user wants, but I definitely don't want it to be stuck in /var/lib/Oldentide either, especially because I'd like to get this to compile on Windows too someday.  

Personally I much prefer to have the db file directly in the Oldentide subfolders.  This was the exact reason why I used sqlite  (a single, portable, easy to back up database file) instead of mysql or the like.  See [digitalocean.com article](https://www.digitalocean.com/community/tutorials/sqlite-vs-mysql-vs-postgresql-a-comparison-of-relational-database-management-systems) about different database programs, especially under "Advantages of SQLite"

My reasoning for putting it in Oldentide/Server/db/Oldentide.db is that it is completely logical to the user what is stored there.  I think the file hierarchy itself helps the user find the database file if they want to edit it manually, back it up or copy it to another machine.  Sqlite3 opens up database files the same no matter where they are stored.  MySQL stores its databases as a mixture of different files and formats.

I think the simplicity of the current design is its strongest merit.

**Comment by ajgoda90** [comment]
As an alternative to both those options, how about making the database location configurable with a default to the relative path?

**Comment by hintron** [comment]
My question is: is there a way to make the db relative to the executable in the Oldentide subfolders while at the same time being able to put the executable in the system path, so it can run it from anywhere in the system? We wouldn't want to force the user to `cd` into a specific folder every time. 

To have the db truly relative to the executable seems harder than it sounds - or at least [more OS-specific than I would wish](http://stackoverflow.com/a/933996/1416379). Maybe a config file with a default path is the easiest way.

**Comment by Jldevictoria** [comment]
This is something I don't really want to implement right now.  I like the concept of a fixed fiole structure for the server.  If a user wants to swap databases, they can rename the default Oldentide.db to something else and replace it with their database.
