### ISSUE TITLE
Investigate a thread pool system for packet handling on server.

### ISSUE THREAD

**Issue by Jldevictoria** [Victory-Game-Studios/Oldentide#31]
As the logic required for handling each packet directed to the server grows, the time between when the server is busy and can't receive another packet also grows.  This could potentially result in missing packets at the server due to not listening.

One suggested architecture is to have a dedicated listener thread who is constantly blocking and awaiting a packet to arrive.  When a packet arrives (Event!) the listener will create another thread for handling the packet and return to listening.  

We can use a pool of threads or an ad-hoc thread generation to try to improve performance.

**This is a lot priority issue, and should be delayed until deemed necessary.**

**Comment by hintron** [comment]
How long does it take to spawn a thread process before the listening thread gets back to listening again? Won't there still be a small time where an incoming packet could bounce off and not stick?

**Comment by Jldevictoria** [comment]
Theoretically yes, but its really small if you have a pool of threads ready to go.

**Comment by hintron** [comment]
I'm guessing we would want this for the client as well eventually, right?

**Comment by Jldevictoria** [comment]
The Client is much less likely going to need such a system... I was kinda thinking of having the server simply resend packets if they client doesn't ack them (until the client is deemed disconnected.)

**Comment by hintron** [comment]
We might want to look into the "Event Loop" design:
*Is [libuv](url) something we might want to use? Or is it overkill, since we don't need to be cross-platform? 
*Could we mimic libuv's design and implement our own event loop?
*What is epoll and can it help us?
*Are there other libraries or system calls that could help us?

**Comment by hintron** [comment]
From Joseph:


> We need one thread that contiually performs the "while(listen)" loop in Server::Run().
But we need to add in a queue that receives packets at one end, and dispenses them at the other.
> This first thread will place each new packet into the queue, and then each handler thread will continually look to see if there is a new packet at the head of the queue to take over.
>
> Yeah event loop is basically what I think we need to do, I just call the events packets though.
> I'm already using pthread for the AdminShell, I dont think it would take much work to get other aspects of the server multithreaded...
> 
> We basically need:
> * The listener thread (Listens for new packets, and stuffs them into an event/packet queue)
> * Several handler threads (repeatedly check the front of the queue for new packets to handle)
> 
> They should all share a common GameState and SQLConnector, and have some basic way of verifying that they handle the packets in order.

**Comment by hintron** [comment]
Just implemented a thread-pool architecture using a queue for packets, and it works perfectly! ...famous last words.

I was able to make the TestClient throw as many packets as it could at the Server configured to run with 10 worker threads. 26 million connection packets later, it still wasn't even breaking a sweat. The packet queue never seemed to get over 500 because the worker threads were consuming them so well.

Of course, once there is more logic and I/O associated with each packet (e.g. communicating with the database), I imagine things will be more intensive. But for now, it seems to work well. The code could probably be optimized more, but for now, it is fairly simple and straightforward.

![packets2](https://cloud.githubusercontent.com/assets/9166578/25474030/f410ea68-2aee-11e7-9879-ffd5ac759729.PNG)
![packets4](https://cloud.githubusercontent.com/assets/9166578/25474031/f410df0a-2aee-11e7-9f26-b57756bf0c0c.PNG)
