### ISSUE TITLE
Multiple accounts with same email currently not allowed

### ISSUE THREAD

**Issue by hintron** [Victory-Game-Studios/Oldentide#36]
Currently, users are not allowed to register for multiple accounts using the same email for the Oldentide webserver. Is there a specific reason for this?

See Oldentide/Website/router.js under the register endpoint. It checks for previous accounts with the same name OR the same email.

**Comment by jr00t2** [comment]
Thats basically because username and email should be unique... In the game we want to "copy" so called dualboxers werent allowed ofc u can just use another email to register but most games only allow one email per account.
Its more like a feature than a bug :D

**Comment by ajgoda90** [comment]
If we did want to allow dual boxing(TIL a new term), then letting one account have multiple characters would be the way to approach it.

**Comment by hintron** [comment]
So since anyone can get around this by having multiple email aliases, why should we care about restricting it?

**Comment by ajgoda90** [comment]
Leaving emails as a unique identifier has a number of advantages. For instance it simplifies username/password recovery. If we had multiple accounts with the same email, then which password do we reset? Do we need to worry about duplicates if we're sending out notifications? Or what happens if a user changes the email for an account?

**Comment by Jldevictoria** [comment]
I strongly suggest one account per email.

I don't have a problem with people having more than one account as long as they aren't playing with both at the same time, but I agree with Adam that it is easier to manage an account with a unique email.

I never liked multi-boxing, because I felt like it reduced the need for careful character planning, reduced willingness of people to play with each other, and gave a significantly unfair advantage to the multiboxers.

**Comment by Jldevictoria** [comment]
Also we are going to allow 10 character slots per account, so hopefully they wont need multiple accounts.

**Comment by hintron** [comment]
As long as the usernames are unique, I don't see how having non-unique emails makes it harder to manage. You just specify the username of the account you want recovered. But if that's how we want it, that's fine, it just seems like the email used once restriction doesn't actually do anything.

**Comment by Jldevictoria** [comment]
It doesn't do anything to the server, but it does de-incentivise the user to create multiple accounts...

**Comment by ajgoda90** [comment]
Letting a user request a forgotten username can be a helpful feature as well, so unique emails would help with that.

**Comment by hintron** [comment]
Ok, I think these are good reasons. I'll go ahead close the thread.
