### ISSUE TITLE
Log-in Back-End Created

### ISSUE THREAD

**Issue by Jldevictoria** [Victory-Game-Studios/Oldentide#6]
Create all the necessary classes and hooks to implement a functional internet login server from the back-end.  This should include a database, login server, and protocol for requests.

**Comment by hintron** [comment]
I think this is finished

**Comment by Jldevictoria** [comment]
Maybe just put a quick summary of how its being done and then close this issue then.

**Comment by hintron** [comment]
Log-in back-end works fine for the moment. Closing issue.

Summary of the changes:

- Class LoginManager was created for client-side key generation from a password.
- Class AccountManager was created to authenticate keys passed from the client (This could probably be absorbed into GameState; I created this separate class because it uses OpenSSL/bn when GameState doesn't).
- Created mdtest.cpp to test openssl hashing. This can probably be removed now.
- Created PasswordClient to test out functions. This can probably be removed now.
- Added a lot of functionality to SQLConnector and changed the SQL schema to accommodate account creation, key storage, and authentication.
